/* eslint-disable prettier/prettier */
import { type IUser, type GameShip, type Ship } from '@/types/types.ts';

const uuid1 = 'dad63ad0-ce57-4e8f-9bee-57bca673c2d9';
const uuid2 = '58c01699-f309-4f46-bc27-ea2b7bba517f';
export const uuidGame = '853af16e-09a5-4c61-9423-1cc0f11cfa14';

export const user1: IUser = {
  name: 'user 1',
  index: uuid1,
}

export const user2: IUser = {
  name: 'user 2',
  index: uuid2,
}

export const ships1: Ship[] = [
  { position: { x: 4, y: 3 }, direction: true, length: 4, type: 'huge' },
  { position: { x: 7, y: 0 }, direction: true, length: 3, type: 'large' },
  { position: { x: 1, y: 8 }, direction: false, length: 3, type: 'large' },
  { position: { x: 0, y: 0 }, direction: true, length: 2, type: 'medium' },
  { position: { x: 1, y: 4 }, direction: true, length: 2, type: 'medium' },
  { position: { x: 8, y: 5 }, direction: false, length: 2, type: 'medium' },
  { position: { x: 9, y: 0 }, direction: false, length: 1, type: 'small' },
  { position: { x: 3, y: 1 }, direction: true, length: 1, type: 'small' },
  { position: { x: 7, y: 7}, direction: false, length: 1, type: 'small' },
  { position: { x: 9, y: 9}, direction: true, length: 1, type: 'small' },
];

export const shipsGame1: GameShip[] = [
  { position: { x: 4, y: 3 }, direction: true, length: 4, type: 'huge',
    status: 'alive', cells: [{ x: 4, y: 3 }, { x: 4, y: 4 }, { x: 4, y: 5 }, { x: 4, y: 6 }],
    borderCells: [
      { x: 3, y: 2 }, { x: 4, y: 2 }, { x: 5, y: 2 },
      { x: 3, y: 3 }, { x: 5, y: 3 },
      { x: 3, y: 4 }, { x: 5, y: 4 },
      { x: 3, y: 5 }, { x: 5, y: 5 },
      { x: 3, y: 6 }, { x: 5, y: 6 },
      { x: 3, y: 7 }, { x: 4, y: 7 }, { x: 5, y: 7 },
    ] },
  { position: { x: 7, y: 0 }, direction: true, length: 3, type: 'large' ,
    status: 'alive', cells: [{ x: 7, y: 0 }, { x: 7, y: 1 }, { x: 7, y: 2 }], borderCells: [
      { x: 6, y: 0 }, { x: 8, y: 0 },
      { x: 6, y: 1 }, { x: 8, y: 1 },
      { x: 6, y: 2 }, { x: 8, y: 2 },
      { x: 6, y: 3 }, { x: 7, y: 3 }, { x: 8, y: 3 },
    ]},
  { position: { x: 1, y: 8 }, direction: false, length: 3, type: 'large' ,
    status: 'alive', cells: [{ x: 1, y: 8 }, { x: 2, y: 8 }, { x: 3, y: 8 }], borderCells: [
      { x: 0, y: 7 }, { x: 0, y: 8 }, { x: 0, y: 9 },
      { x: 1, y: 7 }, { x: 2, y: 7 }, { x: 3, y: 7 },
      { x: 1, y: 9 }, { x: 2, y: 9 }, { x: 3, y: 9 },
      { x: 4, y: 7 }, { x: 4, y: 8 }, { x: 4, y: 9 },
    ]},
  { position: { x: 0, y: 0 }, direction: true, length: 2, type: 'medium' ,
    status: 'alive', cells: [{ x: 0, y: 0 }, { x: 0, y: 1 }], borderCells: [
      { x: 0, y: 2 }, { x: 1, y: 0 }, { x: 1, y: 1 }, { x: 1, y: 2 }
    ]},
  { position: { x: 1, y: 4 }, direction: true, length: 2, type: 'medium' ,
    status: 'alive', cells: [{ x: 1, y: 4 }, { x: 1, y: 5 }], borderCells: [
      { x: 0, y: 3 }, { x: 1, y: 3 }, { x: 2, y: 3 },
      { x: 0, y: 4 }, { x: 2, y: 4 },
      { x: 0, y: 5 }, { x: 2, y: 5 },
      { x: 0, y: 6 }, { x: 1, y: 6 }, { x: 2, y: 3 },
    ]},
  { position: { x: 8, y: 5 }, direction: false, length: 2, type: 'medium' ,
    status: 'alive', cells: [{ x: 8, y: 5 }, { x: 9, y: 5 }], borderCells: [
      { x: 7, y: 4 }, { x: 8, y: 4 }, { x: 8, y: 4 }, 
      { x: 7, y: 5 }, 
      { x: 7, y: 6 }, { x: 8, y: 6 }, { x: 9, y: 6 }, 
    ]},
  { position: { x: 9, y: 0 }, direction: false, length: 1, type: 'small' ,
    status: 'alive', cells: [{ x: 9, y: 0 }], borderCells: [
      { x: 8, y: 0 }, { x: 8, y: 1 }, { x: 9, y: 1 }
    ]},
  { position: { x: 3, y: 1 }, direction: true, length: 1, type: 'small' ,
    status: 'alive', cells: [{ x: 3, y: 1 }], borderCells: [
      { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 },
      { x: 2, y: 1 }, { x: 4, y: 1 },
      { x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 },
    ]},
  { position: { x: 7, y: 7}, direction: false, length: 1, type: 'small' ,
    status: 'alive', cells: [{ x: 7, y: 7}], borderCells: [
      { x: 6, y: 6}, { x: 7, y: 6}, { x: 8, y: 6},
      { x: 6, y: 7}, { x: 8, y: 7},
      { x: 6, y: 8}, { x: 7, y: 8}, { x: 8, y: 8},
    ]},
  { position: { x: 9, y: 9}, direction: true, length: 1, type: 'small' ,
    status: 'alive', cells: [{ x: 9, y: 9}], borderCells: [
      { x: 8, y: 8}, { x: 9, y: 8}, { x: 8, y: 9}
    ]},
];

export const gameBoardNull = [
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
]

export const gameBoard1 = [
  [
    { isShoot: false, ship: 3 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 1 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 6 },
  ],
  [
    { isShoot: false, ship: 3 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 7 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 1 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 1 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 0 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: 4 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 0 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: 4 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 0 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 5 },
    { isShoot: false, ship: 5 },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 0 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 8 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: 2 },
    { isShoot: false, ship: 2 },
    { isShoot: false, ship: 2 },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
  ],
  [
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: null },
    { isShoot: false, ship: 9 },
  ],
]

export const ships2: Ship[] = [
  { position: { x: 4 , y: 2 }, direction: false, length: 4, type: 'huge' },
  { position: { x: 2, y: 5 }, direction: true, length: 3, type: 'large' },
  { position: { x: 6, y: 5 }, direction: false, length: 3, type: 'large' },
  { position: { x: 1, y: 1 }, direction: true, length: 2, type: 'medium' },
  { position: { x: 7, y: 7 }, direction: false, length: 2, type: 'medium' },
  { position: { x: 4, y: 9 }, direction: false, length: 2, type: 'medium' },
  { position: { x: 6, y: 0 }, direction: true, length: 1, type: 'small' },
  { position: { x: 9, y: 3 }, direction: false, length: 1, type: 'small' },
  { position: { x: 4, y: 4 }, direction: true, length: 1, type: 'small' },
  { position: { x: 4, y: 7 }, direction: false, length: 1, type: 'small' },
];
