export interface WsRequest {
  type:
    | 'reg'
    | 'update_winners'
    | 'create_room'
    | 'add_user_to_room'
    | 'create_game'
    | 'update_room'
    | 'add_ships'
    | 'start_game'
    | 'attack'
    | 'randomAttack'
    | 'turn'
    | 'finish';
  data: string;
  id: number;
}

export interface LoginRequest {
  name: string;
  password: string;
}

export interface LoginResponse {
  name: string;
  index: number | string;
  error: boolean;
  errorText: string;
}

export interface IUser {
  name: string;
  index: string;
}

export interface Winner {
  name: string;
  wins: number;
}

export interface AddUserToRoom {
  indexRoom: number | string;
}

export interface CreateGame {
  idGame: string;
  idPlayer: string /* generated by server id for player in the game session, not enemy (unique id for every player) */;
}

export interface GameInfo {
  idGame: string;
  users: RoomUser[];
}

export interface UpdateRoom {
  roomId: number | string;
  roomUsers: IUser[];
}

export interface RoomUser extends IUser {
  name: string;
  index: string /* user uuid in DB */;
  idPlayer: string;
}

export interface AddShips {
  gameId: number | string;
  ships: Ship[];
  indexPlayer: string;
}

export interface Coordinates {
  x: number;
  y: number;
}

export interface Ship {
  position: Coordinates;
  direction: boolean;
  length: number;
  type: 'small' | 'medium' | 'large' | 'huge';
}

export interface GameShip extends Ship {
  status: 'alive' | 'shot' | 'killed';
  cells: Coordinates[];
  borderCells: Coordinates[];
}

export interface Cell {
  isShoot: boolean;
  ship: number | null;
}

export interface StartGame {
  ships: Ship[];
  currentPlayerIndex: number | string;
}

export interface Attack {
  gameId: number | string;
  x: number;
  y: number;
  indexPlayer: number | string;
}

export interface RandomAttack {
  gameId: number | string;
  indexPlayer: number | string;
}

export interface AttackFeedback {
  position: Coordinates;
  currentPlayer: string;
  status: 'miss' | 'killed' | 'shot';
}

export interface Turn {
  currentPlayer: number | string;
}

export interface FinishGame {
  winPlayer: number | string;
}
